export default {
  index: 'Introduction',
  '---get-started': { type: 'separator', title: 'Get Started' },
  'getting-started': 'Getting Started',
  'file-browser': 'File Browser',
  'detail-panel': 'Detail Panel',
  '---guides': { type: 'separator', title: 'Guides' },
  'github-integration': 'GitHub Integration',
  'git-actions': 'Git Actions',
  'ai-commit-messages': 'AI Commit Messages',
  'diff-viewer': 'Diff Viewer',
  '---reference': { type: 'separator', title: 'Reference' },
  settings: 'Settings',
  'keyboard-shortcuts': 'Keyboard Shortcuts',
  '---resources': { type: 'separator', title: 'Resources' },
  faq: 'FAQ',
  'release-notes': '',
};
